// USER action types
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

// swipe screen project action types

export const LOAD_SWIPE_PROJECTS = 'LOAD_PROJECTS';
export const LOAD_SWIPE_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_SWIPE_PROJECTS_FAIL = 'LOAD_PROJECTS_FAIL';
